adding a transition to jobs pages
Granola-Team/site pull request #23
Opened 2022-09-29 19:02 UTC by jstavh

This PR allows each job posting box to be highlighted when the mouse is on top of it (hover) and customized the transition period to be the fastest option in tailwind.

2022-09-29 19:03 UTC, jstavh commented
There is a conflict because the merge depends on jason-career-layout branch as the main branch does not have any job postings to attach this PR to.

2022-09-30 20:44 UTC, robinbb requested changes

2022-09-30 20:44 UTC, robinbb commented on src/astro/src/pages/careers/jobs-1.mdx
> +---
Remove this file.

2022-09-30 20:44 UTC, robinbb commented on src/astro/src/pages/careers/jobs-2.mdx
> +---
Remove!

2022-09-30 21:01 UTC, robinbb approved these changes

2022-09-30 21:01 UTC, merged