button created and displayed on individual job postings but not caree…
Granola-Team/site pull request #24
Opened 2022-09-29 19:46 UTC by jstavh

Join our team yellow written button appears in individual job postings but not on the career page. The order is now branch jason-button into-> jason-transition -> jason-career-layout -> main. Homepage does not point to the career page yet, which is next up with a nav-bar.

2022-09-30 20:53 UTC, robinbb requested changes

2022-09-30 20:53 UTC, robinbb commented on src/astro/src/components/Join.astro
> +        <a href="mailto:hello@granola.team" class="py-4 px-8 rounded-lg text-yellow-300 no-underline text-2md
Change to Granola colour.

2022-09-30 21:13 UTC, robinbb approved these changes

2022-09-30 21:15 UTC, robinbb requested changes
Join button still appears.

2022-09-30 22:59 UTC, jstavh commented
> Join button still appears.

I believe because we are wrapping dynamic routing [...page].astro page with <CareersLayout> <CareersLayout /> we need Join function in both. Does this make sense?

2022-10-01 02:43 UTC, robinbb commented
Join button now appears twice on /careers page.

2022-10-02 03:57 UTC, jstavh commented
npm run dev shows the button only once. I'm working on finding a way to get the netlify preview to match this.

2022-10-05 20:40 UTC, robinbb commented
I have made improvements to the build which ensure that any evidence of a prior build is removed. ('npm run clean') This is on another branch (and PR), and I have merged that branch onto this one.

Still, both buttons appear on the preview. They also appear for me when I run 'npm run dev' or 'npm run preview'. In other words, there are 2 buttons appearing due to the logic in this PR (which is therefore incorrect, and in need of correction). They may not be appearing on *your* screen due to the size of your screen. You will see them in the "view source" on your preview, likely, @jstavh.

2022-10-05 23:31 UTC, closed without merging