nav bar created and changes size at one breaking point
Granola-Team/site pull request #25
Opened 2022-09-29 19:52 UTC by jstavh

Created a nav bar that points homepage to careers page. It changes size at one breaking point that changes size for small screens (phones) to large screens (computers). This is higher than the jason-button branch

2022-09-30 20:56 UTC, robinbb requested changes
Make PR against 'main' so that I can see a Netlify preview.

2022-09-30 20:56 UTC, robinbb commented on src/astro/src/components/Nav.jsx
> +// import * as React from 'react';
Remove commented out code.

2022-09-30 22:55 UTC, jstavh commented on src/astro/src/components/Nav.jsx
> +// import * as React from 'react';
Removed comments.

2022-10-01 02:46 UTC, robinbb commented
@jstavh Please modify Netlify settings so that *any* PR generates a preview, if possible.

2022-10-02 04:11 UTC, jstavh commented
Netlify settings are set to preview every PR. I will need to continue to investigate why no preview is showing up here. I made these selections on Netlify via these instructions: Site settings > Build & deploy > Continuous Deployment > Deploy Previews.

2022-10-05 20:41 UTC, robinbb commented
Netlify is probably confused because this PR was originally made against another base branch, and then converted into a PR against 'main'. You will have to re-create the PR, @jstavh .

2022-10-05 23:04 UTC, closed without merging