Access Blog
Granola-Team/site pull request #61
Opened 2023-10-13 18:00 UTC by jstavh

Ability to access blog from home page via button. Addresses https://github.com/Granola-Team/site/issues/52

2023-10-16 21:48 UTC, jstavh commented
The above commit x addresses further developments requested:

- To create a nav button for the blog
- To remove the "Mina FAQ" button from the home page
- To transform the Mina FAQ into a regular blog article
- To create an index for all blog articels (of which there would then be exactly 2)
- ... which would allow me to write further blog articles in the 'blog' directory, in Markdown.

2023-10-18 19:42 UTC, robinbb requested changes
Looking good! Please add a link to the blog page from the home page, possibly a button replacing tho old "Mina FAQ" or some other nav link. Also, why does the deploy preview send me directly to the "blog" page on this PR, instead of to the home page?

2023-10-18 22:00 UTC, jstavh commented
> add a link to the blog page from the home page, possibly a button replacing tho old "Mina FAQ" or some other nav lin

@robinbb -- fixed all :slightly_smiling_face:

2023-10-19 15:41 UTC, robinbb approved these changes

2023-10-19 15:41 UTC, merged